version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: laravel-redis

    mysql:
      image: mysql:5.7
      container_name: laravel-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=laravel
        - MYSQL_USER=laravel
        - MYSQL_PASSWORD=root
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: laravel-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: docker/php-fpm
      container_name: laravel-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
